### PR TITLE
Combine Shunted model with Cross-prediction

### PR DESCRIPTION
**Pull request by drkostas**

### CODE REVIEW

**Comment by andreicozma1** [comment]
Should we try to move these class definitions to individual files?

**Comment by drkostas** [comment]
> Should we try to move these class definitions to individual files? models_mae is becoming really large

That's a good idea, should I create 3 files `models_mae_base.py` `models_mae_shunted.py` `models_mae_shunted_cross.py`, and import all of them in `models_mae.py`?

**Comment by drkostas** [comment]
How does [this](https://github.com/aicip/SatMAE/pull/12/commits/c2feb459f8ac6c1692b103ec71955cacf9cab956) look @andreicozma1 ?

**Comment by andreicozma1** [comment]
> How does [this](https://github.com/aicip/SatMAE/pull/12/commits/c2feb459f8ac6c1692b103ec71955cacf9cab956) look @andreicozma1 ? I made it so we don't have to change the imports anywhere when import models_mae is called, the **init**.py of the models_mae folder is referenced

Looks great! So clean!

**Review by andreicozma1 — APPROVED** [review]
All looks good from my side!

**Pull request merged**
